version: 2

build:
  image: latest
  apt_packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

# doc/requirements.txt fixes https://github.com/sphinx-doc/sphinx/issues/9783
python:
  version: 3.7
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt
