version: 2

build:
  image: latest
  apt_packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

python:
  version: 3.7
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
