#!/usr/bin/env python3

import argparse
import logging
import sys

import nibabel
import numpy


def correction(filename, ofilename, min, max):
   
    img = nibabel.load(filename)
    data = img.get_data().astype(numpy.float32)
    
    data[ data < int(min) ] = int(min)
    data[ data > int(max) ] = int(max)
        
    oimg = nibabel.Nifti1Image(data, img.affine)
    nibabel.save(oimg, ofilename)
        

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Correction of abnormal values after running qMRI scripts.")
    
    parser.add_argument("filename", help="Path to the NIfTI file to check.")
    parser.add_argument("ofilename", help="Path to the NIfTI after correction (can be the same).")
    parser.add_argument("mask", help="Mask into the correct study space.")
    parser.add_argument("min", help="Min value.")
    parser.add_argument("max", help="Max value.")
    args = vars(parser.parse_args())
    
    try: 
        sys.exit(correction(**args))
    except Exception as e:
        if logging.getLogger().getEffectiveLevel() <= logging.DEBUG:
            raise
        else:
            parser.error(e)
